package com.simionato.inventarioweb.models

data class EmpresaModel(var id: Int,
                        var cnpj_cpf:String ,
                        var razao:String ,
                        var fantasi:String ,
                        var inscri:String ,
                        var cadastr:String ,
                        var ruaf:String ,
                        var nrof:String ,
                        var complementof:String ,
                        var bairrof:String ,
                        var cidadef:String ,
                        var uff:String ,
                        var cepf:String ,
                        var tel1:String ,
                        var tel2:String ,
                        var email:String ,
                        var obs:String ,
                        var user_insert: Int,
                        var user_update: Int) {
    constructor() : this(
        0,
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        "",
        0,
        0,
    )
}
