package com.simionato.inventarioweb.models

data class UsuarioModel(val id_empresa: Int,
                        val id: Int,
                        val razao: String ,
                        val cnpj_cpf: String ,
                        val cadastr: String ,
                        val rua: String ,
                        val nro: String ,
                        val complemento: String ,
                        val bairro: String ,
                        val cidade: String ,
                        val uf: String ,
                        val cep: String ,
                        val tel1: String ,
                        val tel2: String ,
                        val email: String ,
                        val senha: String ,
                        val pasta: String ,
                        val grupo: Int,
                        val ativo: String ,
                        val timer: String ,
                        val ticket: String ,
                        val man_hora_entrada: String,
                        val man_hora_saida: String ,
                        val tard_hora_entrada: String ,
                        val tard_hora_saida: String ,
                        val user_insert: Int,
                        val user_update: Int,
                        val gru_descricao: String)
